# Generated by Django 5.2.1 on 2025-06-04 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='spot',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AddField(
            model_name='parkingzone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkingzone',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingzone',
            name='available_spots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parkingzone',
            name='coordinates',
            field=models.CharField(help_text='Latitude,Longitude', max_length=100),
        ),
        migrations.AlterField(
            model_name='parkingzone',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='parkingzone',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='parkingzone',
            name='total_spots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ParkingSpot',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
